### ISSUE TITLE
The extension appears to be totally broken

### ISSUE THREAD

**Issue by joetriccas** [spdermn02/TouchPortal_ITunes_Plugin#10]
Howdy,

No idea of the root cause, but this extension simply no longer works.

Considering the etensio had no update I'm obliged to adssume something changed on the iTunes API side of things.

**Comment by spdermn02** [comment]
can you make sure `include plug-in logs` is checked on the Logs tab of Touch Portal
and then restart the plugin itself, or all of touch portal, and send a copy of your log.txt to %APPDATA%\TouchPortal

there is a known issue that will crash the plugin if you play any content outside of your `Library` but that is the only known problem at this time. I use this plugin daily, so unsure if iTunes changed anything or not but mine still functions correctly

**Comment by joetriccas** [comment]
Ah - that would probably explain the issue I have been seeing as I have a couple playlists that I have added but they update automatically and I'm guessing the songs don't get added to my library. I'll take a look into it and if there is anything further I'll add it here. I'll aim to get that sorted by the weekend as quite busy with work atm for the next couple days :D - thanks for the swift response and apologies if this is a red herring!

**Comment by spdermn02** [comment]
no worries. Yeah - I really need to look at a better processing for outside Library playing. There was another user originally doing a rewrite of the entire plugin, but I think he got busy with work and family and had to put it on hiatus for the moment. Thanks for understanding. I'll put this back on my list to review as soon as I can.

**Comment by joetriccas** [comment]
Heya, I tied this and I see this error:
09:37:52.932 - [LOG] (Action Flow) Button Pressed at (1, 1) on Page: \TPiTunes-Full-3.0.0Update.tml
09:37:52.933 - [LOG] (Action Flow)  - Doing action: [Play iTunes Playlist] itunes_playlists -> StreamBeats - EDM | itunes_shuffle_playlist -> On | itunes_repeat_playlist -> Playlist | 
09:37:52.936 - [LOG] (Plugin Instance) Preparing plugin data for TPiTunes
09:37:52.940 - [LOG] (Plugin Instance) This is TPiTunes and received message for TPiTunes
09:37:52.943 - [LOG] (Plugin Instance) Sending outgoing message failed: java.net.SocketException: Connection reset by peer

THere's loads of other stuf in the logs so I didn't upload but if you ned it let me know

**Comment by joetriccas** [comment]
[log.txt](https://github.com/spdermn02/TouchPortal_ITunes_Plugin/files/8618892/log.txt)
Here's the full file from a restart of TP

**Comment by spdermn02** [comment]
yeah - that's odd.. I use that same playlist. and have had no issues.  It's like the process is just dying.. but not reporting what is going on. Nothing in the new log from the restart of TP indicates an issue, i see the update states process running (probably need to limit that message from being printed for future release) but nothing seems to be broken yet.

**Comment by joetriccas** [comment]
For context - I reinstaled windows a week ago. I was having this issue prior to the reinstall and hoped that reinstalling would clear everything out.

Also, my install of iTunes if from the windows store not the Apple website - I know there are some differences not sure if that could be the cause? I can't remember which the original install was, that I did have working

**Comment by joetriccas** [comment]
It is writting out that Econnreset on the websocket though so not sure if possibly this is a windows app vs standalone issue

**Comment by joetriccas** [comment]
Okay so today I tried a different load order. I opened OBS, then touch portal and that automagically opened itunes and now it's working...? Weird. I will close and hid in a corner somewhere.

Thanks for that small chunk of yur finite existence - testers love a red herring!
