### ISSUE TITLE
Is this Plugin Still working?

### ISSUE THREAD

**Issue by JNR8** [spdermn02/TouchPortal_ITunes_Plugin#4]
I installed the pluging, and i can see the Actions in the list.  iTunes is open.  None of the actions do anything.  
iTunes version: 12.10.8.5

I followed the setup instructions, which were pretty simple for adding the plugin to Touch Portal.  Is ther something else that needs to done that is not listed in the readme file?

**Comment by spdermn02** [comment]
Yea this plugin still works. Are you using Apple Music or your own Local Music? There was another user that was using his own music as he doesn't have Apple Music and found a few bugs I need to fix. One of them is related to album artwork, which there is a config option to turn that off and then restart TP to restart the software. You could also check to see if tpitunes.exe is still running in the "Details" tab of the Windows task manager. I do have it on my list of things to research hopefully this week.

**Comment by JNR8** [comment]
I think I was a bit hasty.  it seems after a restart of the my PC every is working fine.  

Would it be possible to add events to the plugin?  I'd like to be able to create as little buttons as possible and be able to trigger different actions baced on the state of itunes would be handy  (i.e. if a playlist was already playing taping the same button ould toggle play and pause etc, or be able to create a Play/Pause button where the icon changes depend on the state).

**Comment by spdermn02** [comment]
Hmmm. You could do that without additional states from the plugin. However if you started the playlist from iTunes itself, it would make it more difficult. I think I should be able to get the current playlist name, and make a state for that (maybe I already did, I can't remember) I'll have a look this weekend hopefully.  Thanks for the response too! There are still enhancements and error checking I need to make, but glad it started working!

**Comment by spdermn02** [comment]
I'll keep this open until I get a look again and see what I can do.
