### ISSUE TITLE
Artwork only created when new track is played, not when resuming from pause state

### ISSUE THREAD

**Issue by JNR8** [spdermn02/TouchPortal_ITunes_Plugin#5]
I am attempting to have artwork played during a stream, but in order for the artwork to not be shown in OBS when I have stopped playing music I have to set TP to delete the file album_artwork_temp_orig.png when the play state of iTunes is stopped.  

But when I start playing the same track again the file album_artwork_temp_orig.png is not recreated, so I end up with the Artist Name and Track Name without album art until the next track is played and the file is recreated.  Would it be possible to have the file recreated each time the iTunes plays a track whether it be next track or from a paused state?

**Comment by spdermn02** [comment]
i'll look into it thanks.

**Comment by spdermn02** [comment]
This should be resolved with 3.0.0 update - let me know if it doesn't.
