### ISSUE TITLE
Volume control doesn't work

### ISSUE THREAD

**Issue by joetriccas** [spdermn02/TouchPortal_ITunes_Plugin#7]
Hey,

Using an iPad 2 (old I know) running touch portal, I have installed the plug in and have all functionality other than the volume up and down working.

I can see the latest file states in the release note that this should be fixed, so I'm curious if you're certain?

I have tried totally removing the plug in, redownloading the latest version and it's still not working. I not also that the version number in Touch Portal is not incremented and still displays 2000:
![image](https://user-images.githubusercontent.com/85166160/126199293-ff0f9d39-90c7-4aa8-871a-7fd034b8cc4c.png)

If you need any other info let me know.

**Comment by spdermn02** [comment]
Well, it should be working. But I'll double check to make sure. As I don't use the volume inside iTunes much I may have broken it and thought I fixed it.

**Comment by spdermn02** [comment]
I believe this to be fixed Please open a new ticket if it is not.
