### ISSUE TITLE
Volume button is not in the provided iTines template page and cannot be imported

### ISSUE THREAD

**Issue by joetriccas** [spdermn02/TouchPortal_ITunes_Plugin#9]
Howdy Spidey!

Great work on this latest version, it's much more stable and performant :D.

I've noticed that the templated TouchPortal page you provide woks fine with one exception, the volume slider isn't displaying.

I went digging and found you have also provided a tmeplate for that button in particular, however when I attempt to import it into the volume slider position of the template it seems to just do nothing. This could totally be me not understanding something about TouchPortal file formats etc, but figured I'd raise it

**Comment by joetriccas** [comment]
![image](https://user-images.githubusercontent.com/85166160/150516513-c6066175-12f1-4103-add8-51b27d4d166e.png)
As you can see there is no volume slider or display

**Comment by joetriccas** [comment]
Here's me attempting to import the button. worth noting that I was unable to download the actual file from your repo so I just created a basic text doc, pasted in the contents from github and then renamed it's file extension to match the file in your repo
![TouchPortalVolumeButton](https://user-images.githubusercontent.com/85166160/150517210-7cb3f083-2945-4145-b9fd-882ba49e4603.gif)

**Comment by spdermn02** [comment]
Hey, thanks for using the plugin. One thing is for sure the problem, you are on an old version of Touch Portal. There has been a major update to 3.0 which will allow the slider functionality to work. 

What you need to do is create a backup, uninstall touch portal, download new installer from the touch-portal.com website and install it. Also make sure your mobile device software is updated as well to take advantage of it. 

The application should load all your pages and setup fine. But make sure you do the uninstall before installing the newest version. 

Let me know the results.

**Comment by spdermn02** [comment]
issue would be that newest version with actual slider requires 3.0 of TP to work.
